### ISSUE TITLE
Convert option always greyed out

### ISSUE THREAD

**Issue by alan-signal** [dethlex/NumberConverter#1]
This is in CLion with a rust file, I'm not sure if you intended to support this scenario or not.

![image](https://user-images.githubusercontent.com/48254818/127655113-7d7c03a9-b8a4-4dcb-9b5b-7bca082acd7e.png)

**Comment by dethlex** [comment]
Hello!
I'm afraid, because symbol "_" in number format is not supported.
I'll add it in next release.
