### ISSUE TITLE
Support shortcuts and multi carets

### ISSUE THREAD

**Issue by krasa** [dethlex/NumberConverter#4]
- Consider registering separate ConvertAction subclass for each type, to allow shortcuts.
- Do not use only #getCurrentCaret, but rather `com.intellij.openapi.editor.CaretModel#getCaretsAndSelections` (afaik they need to be sorted and reversed)

**Comment by dethlex** [comment]
Thanks for your proposal! I think I can do it.

**Comment by krasa** [comment]
There needs to be only one runWriteCommandAction for all carets, or Undo won't work properly.

**Comment by dethlex** [comment]
You're right, I`ll fix it
