### ISSUE TITLE
Request: for Kotlin, support negative-hex value to positive hex-value (of color)

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dethlex/NumberConverter#7]
When Android Studio converts from Java to Kotlin, it often converts numbers that were supposed to be of colors.

So, it creates something like:

```
var someColor = -0x555556
```

The safe way to find what color this is, is to use `Integer.toHexString()`, which would result in `0xffaaaaaa` for this case.

After I do this, the IDE has a tiny preview of the color on the side, so it helps me read it in both ARGB format and visually:

![image](https://user-images.githubusercontent.com/5357526/183905841-810c8d64-7052-47e1-9014-930e46edf1b8.png)

Please offer such a conversion , and auto-add "0x" and ".toInt()" if needed (IDE says it's an Int already), and if ".toInt()" isn't needed, add the type of the field instead.

**Comment by dethlex** [comment]
Hello! Unfortunately, I can't add ".toInt()", because this plugin is independent of the programming language. But I can support proper negative conversion.
Also, you can use multicaret and add ".toInt()" after conversion to all numbers simultaneously.

**Comment by AndroidDeveloperLB** [comment]
@dethlex It's not about the "toInt". Those values are already integers.
It's about the conversion (in code alone) to a more readable format (AARRGGBB instead of something that doesn't look like a color at all), and then add "toInt" because colors are supposed to be integers.

**Comment by dethlex** [comment]
@AndroidDeveloperLB hello, finally I found the time to support this.
As I said before, it's impossible to add "toInt" suffix, 'cause this plugin is independent of using language. But I fully supported negative conversion.
After conversion, you can add "toInt" with multicaret, for example, if you have plenty of numbers.

**Comment by AndroidDeveloperLB** [comment]
@dethlex I don't understand what you did. Can you please show on screenshot/video ?

**Comment by dethlex** [comment]
@AndroidDeveloperLB simply, you can now convert from "-0x555556" to "0xffaaaaaa"

**Comment by AndroidDeveloperLB** [comment]
@dethlex I don't understand how. Is it supposed to add a context menu to selected text?
If so, it doesn't.
I tried to find an action, and found "convert" (not sure if it's of the current plugin or something else), but then it offers other things and the non-negative value isn't one of them:

[studio64_2022-10-06_14-43-15.zip](https://github.com/dethlex/NumberConverter/files/9724474/studio64_2022-10-06_14-43-15.zip)

**Comment by dethlex** [comment]
@AndroidDeveloperLB just wait for the update please (1.5.0 version), it will be in the context menu as before. 
[Screen Recording 2022-10-06 at 3.08.18 PM.mov.zip](https://github.com/dethlex/NumberConverter/files/9724680/Screen.Recording.2022-10-06.at.3.08.18.PM.mov.zip)

**Comment by AndroidDeveloperLB** [comment]
@dethlex Oh sorry. 
Thank you.

**Comment by dethlex** [comment]
@AndroidDeveloperLB you're welcome :)
