### ISSUE TITLE
Bug: some numbers can't be converted well to color hex integer

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [dethlex/NumberConverter#9]
v1.5.0.

In Kotlin, sadly, the IDE keeps converting color-hex values to integers so that I can't see the ARGB values nicely.

For example, when I paste "0xffb11900" (from Java to Kotlin), I get "-0x4ee700".
Another example is when I paste "0x80000000", and get "-0x80000000".

So, what I do is use this plugin to convert it back to hex-integer, and usually it works (except for adding ".toInt()" that I need to add manually).

But, for both of these examples, it doesn't work well:

When I try to convert "-0x4ee700" back to "0xffb11900.toInt()", I get "0xFFFFFFFFFFB11900".
When I try to convert "-0x80000000" back to "0x80000000.toInt()", I get "0xFFFFFFFF80000000".

Please fix this. 
Or, maybe add a conversion of "to ARGB color hex", and in the case that it's in Kotlin, also add ".toInt()" .

**Comment by dethlex** [comment]
@AndroidDeveloperLB hello! Finally, I found the time to make plugin changes. Could you please provide more examples of bad and good cases?

**Comment by dethlex** [comment]
I think I realize the problem, the fix is coming soon

**Comment by AndroidDeveloperLB** [comment]
Sorry I haven't used this for a long time. I think I used it when I converted from Java to Kotlin.
If you know of an alternative of Kotlin to write ".toInt()", please let me know. It's quite annoying compared to in Java...

**Comment by dethlex** [comment]
This feature has been added recently. You can go to settings, enable "surrounding" and write to the right part whatever you want
